[tool.poetry]
name = "polymath-server"
version = "0.1.0.dev54"
description = ""
authors = ["Your Name <you@example.com>"]

packages = [
    { include = "polymath" }
]

[tool.poetry.dependencies]
python = ">=3.8, <3.10"
fastapi = "^0.78.0"
uvicorn = "^0.17.6"
polymath-core = {path = "../polymath_core"}
grpcio = "^1.46.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
