[tool.poetry]
name = "polymath-server-http"
version = "0.1.0.dev142"
description = ""
authors = ["Your Name <you@example.com>"]

packages = [
    { include = "polymath" }
]

[tool.poetry.dependencies]
python = ">=3.8, <3.10"
fastapi = "^0.78.0"
uvicorn = "^0.17.6"

[tool.poetry.dev-dependencies]
polymath-core = {git = "https://github.com/ospark-org/polymoath-core.git", rev = "main"}


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
